### ISSUE TITLE
Startup crashes

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-ios#533]
https://forums.zotero.org/discussion/comment/414345/#Comment_414345

Do these look like crashes we've already fixed?

**Comment by michalrentka** [comment]
@dstillman it looks slightly different, but could as well be fixed by recent changed. It would be nice if he could test the beta build and see if that helps.

**Comment by dstillman** [comment]
Still crashing: https://forums.zotero.org/discussion/comment/414368/#Comment_414368
